package com.java.semantic.model.codefact;

public enum RelationKind {
    REFERENCES,
    CALLS,
    IMPLEMENTS,
    OVERRIDES,
    EXTENDS,
    USES_TYPE,
    USES_ANNOTATION,
    READS_CONFIGURATION,
    USES_SQL_IDENTIFIER,
    CALLS_OUTBOUND_API,
    PUBLISHES_MESSAGE,
    DECLARES_ERROR_CONTRACT
}
